# Generated by Django 2.2.8 on 2022-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmodel',
            name='time',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='14:56:51'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='14:56:51'),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='14:56:51'),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='14:56:51'),
        ),
    ]
