# Generated by Django 2.2.8 on 2022-10-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20221027_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True, default='14:12:34')),
                ('end_time', models.TimeField(blank=True, default='14:12:34')),
                ('locality', models.CharField(max_length=30, null=True)),
                ('creator', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(default='Upcoming', max_length=30)),
                ('slots', models.IntegerField(default=1)),
                ('slot_available', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='creatematchModel',
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='14:12:34'),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='14:12:34'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='14:12:34'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='14:12:34'),
        ),
    ]
